### Crear una nueva tarea
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "titulo": "test",
  "descripcion": "Comprar leche y pan"
}
### Traer todas las tareas
GET http://localhost:3000/api/tasks

### Actualizar una tarea
PUT http://localhost:3000/api/tasks/22
Content-Type: application/json

{
  "status": "test"
}

### Eliminar una tarea
DELETE http://localhost:3000/api/tasks/23


